### ISSUE TITLE
broken?

### ISSUE THREAD

**Issue by tomByrer** [tddbin/es6katas.org#20]
Seems I get nothing but errors in Chrome & Fx in all tests.  For example:
```
`Array.from` converts an array-like object or list into an Array
call `Array.from` with an array-like object ‣
AssertionError: {"0":"one","1":"two","length":2} deepEqual ["one","two"]
    at eval (eval at runSpecs (http://tddbin.com/mocha/spec-runner.js:101580:12), <anonymous>:13:12)
    at r (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:9112)
    at r.o.run (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:9812)
    at o.runTest (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:13250)
    at http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:13824
    at r (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:12787)
    at http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:12763
    at n (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:12554)
    at http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:12618
    at e (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:1:284)
```
&
```
`Set` lets you store unique values of any type
`Set` is a new global constructor function ‣
every value in a set is unique ‣
AssertionError: 1 == 2
    at eval (eval at runSpecs (http://tddbin.com/mocha/spec-runner.js:101580:12), <anonymous>:23:12)
    at r (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:9112)
    at r.o.run (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:9812)
    at o.runTest (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:13250)
    at http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:13824
    at r (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:12787)
    at http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:12763
    at n (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:12554)
    at http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:12618
    at e (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:1:284)
```

**Comment by tddbin** [comment]
This is what those katas are for, you are supposed to solve them in order
to learn some es6 by fixing those. Good luck
Am 13.08.2015 11:47 vorm. schrieb "Tom Byrer" <notifications@github.com>:

**Comment by tomByrer** [comment]
Oh, I guess I didn't read the small print...
thanks
