### ISSUE TITLE
Reflect.construct()` is like new throwing TypeError: CreateListFromArrayLike called on non-object

### ISSUE THREAD

**Issue by demns** [tddbin/es6katas.org#30]
https://www.dropbox.com/s/7i2uycqttrgu2ce/Screenshot%202016-03-12%2011.58.02.png?dl=0

**Comment by demns** [comment]
Some investigation:
Version 49.0.2623.87 m Chrome -- not working
Version 48.0.2564.116 m Chrome -- working
Version whatever Edge -- working

will take a closer look into this in a few hours; right now sending a stacktrace, maybe someone know what I'm doing wrong here :)

`Reflect.construct()` is like new ‣
TypeError: CreateListFromArrayLike called on non-object
    at eval (eval at runSpecs (http://tddbin.com/mocha/spec-runner.js:101580:12), <anonymous>:35:40)
    at r (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:9112)
    at r.o.run (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:9812)
    at o.runTest (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:13250)
    at http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:13824
    at r (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:12787)
    at http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:12763
    at n (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:12554)
    at http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:2:12618
    at e (http://cdnjs.cloudflare.com/ajax/libs/mocha/2.1.0/mocha.min.js:1:284)

**Comment by demns** [comment]
And yes, I can do this as well, but why should I change assert in order to make it work.

`    it('`Reflect.construct()` is like new', function() {
      let Class = Date;
      assert.equal(Reflect.construct(Class, []) instanceof Class, true);
    });
`

**Comment by demns** [comment]
The PR is created fixing this issue. If this is an inappropriate place for such kind of issues, please close it -- I'll recreate it in katas repo
